version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: ais
      POSTGRES_USER: ais_user
      POSTGRES_PASSWORD: ais_pass
    ports:
      - "5432:5432"
